---
title: "Movie Data"
output:
  pdf_document: default
  word_document: default
date: "`r format(Sys.Date())`"
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
setwd("/Users/kalyankankanala/MovieAnalysis")
library(ProjectTemplate)
load.project()
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Introduction
## Context
The film industry contributes a significant amount of revenue globally through cinema sales and streaming platforms. The success of a film depends on multiple factors, which makes it important to identify and analyse the key factors to ensure the continuous profitability of the industry as well as the enhancement of the global economy. In this regard, the current report is concerned with analysing a movie dataset containing data regarding different success factors of movies from 2000 to 2024. The report has utilised the CRISP-DM framework to profoundly analyse data by breaking the process into 2 CRISP-DM cycles. CRISP-DM methodology involves a multi-steped iterative framework for the profound analysis of complex scenarios (Bemthuis et al., 2025). The first cycle has focused on understanding the film industry in terms of exploring the patterns of success, ratings, revenue growth and many more related aspects. The secondary cycle has focused on the in-depth analysis of the influence of genre and language on movie success.

## Research Objectives
First Cycle

To determine the success pattern of movies from 2000 to 2024 by exploring different factors associated with it

To comprehend the connection between a movie's budget and its revenue contribution

To identify the movies associated with high revenue and high ratings, and to comprehend the features most significant for movie success

Second Cycle

To examine the way movie genre impacts the ratings and the commercial success of movies

# First CRISP-DM Cycle
## Business Understanding
The continuously increasing production cost and budgetary constraints have made it difficult to maintain financial sustainability in the film industry (Singh & Asthana, 2025). In this regard, it has become necessary to explore the connection between budget and film success. This cycle involves understanding the business-related aspects of film production companies, emphasising the identification of the key success factors required to be focused on by film producers to ensure movie success. In order to gain this business understanding, the study has divided the main business question into sub-questions defined below.

Research Questions

What are the key patterns of the success factors of movies in the dataset used?

How is the movie budget connected to the movie revenue in the film industry?

What type of changes have the movies experienced over time in terms of release, revenue and rating patterns?

Which movies have received the highest ratings and have generated the highest revenue?
